### ISSUE TITLE
Tabs with tables

### ISSUE THREAD

**Issue by oliveiravhs** [NorwegianVeterinaryInstitute/laksetap#13]
Add a filtering option in the table where the user can type the zone they would like to vizualize. I think this is an option in the package I use for teh table (DT package?). I think this is done only by changing the class of the variable (zone in that case). This may be applicable to other columns too. For example in the dødelighet måned add to the month as well? I mean if this is done for more than one column maybe worth it just to it without the velg år option since they could do it using the table.

**Comment by novica** [comment]
`filter = "top"`  option is not possible because the DT translations somehow breaks the JavaScript behavior of the filter. I cannot resolve that.

**Comment by novica** [comment]
- [ ] implement similar solution for all tables like cohorts
- [ ] filtering for months in the month tables
