### ISSUE TITLE
Tab: dødelighet måned (table)

### ISSUE THREAD

**Issue by oliveiravhs** [NorwegianVeterinaryInstitute/laksetap#14]
- Months are missing in the table
- Less decimals in the numeric columns
- Intervals for mortality missing

**Comment by novica** [comment]
@oliveiravhs  this is tracked in #7 so maybe just tell me  what column names to display and also provide translation.

**Comment by oliveiravhs** [comment]
Sorry will check before the next issues. I think added this in another issue about the translation.
