### ISSUE TITLE
Dødelighet måned (Diagram)

### ISSUE THREAD

**Issue by oliveiravhs** [NorwegianVeterinaryInstitute/laksetap#15]
- Zone 2 is shown only with median that should be removed. We have already have it merged with zone 1. 
 - Investigate possibility of adding more zones for comparisons between each other. Naturally to not conflict with the primary zone this would be built like what we do for Norge that we show only the median.

**Comment by novica** [comment]
resolved in 2e70303d9bfb195ebadfa1dc710dc54841819e34
